### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [ketlrznt/ketlrznt.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by ketlrznt** [comment]
Thank you for your request, and please let me apologize for my quite late response. I've add a screenshot in README.md, and also upload the original screenshot [ketlrznt.png](https://github.com/ketlrznt/ketlrznt.zsh-theme/blob/main/ketlrznt.png). Have a look if you are interested in it! Thanks again!
